spring:
  application:
    name: jira-git-migration
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Neo4j Configuration
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  
  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

# Jira Configuration
jira:
  url: https://your-jira-instance.atlassian.net
  username: your-email@example.com
  api-token: your-api-token
  project-key: PROJECT
  batch-size: 100

# Git Configuration
git:
  repository-path: /path/to/your/git/repository
  branch: main
  max-commits: 1000

# Weaviate Configuration
weaviate:
  url: http://localhost:8080
  api-key: your-weaviate-api-key
  batch-size: 100

# Neo4j Configuration
neo4j:
  uri: bolt://localhost:7687
  username: neo4j
  password: password

# Logging Configuration
logging:
  level:
    com.jiragit: DEBUG
    org.springframework.data.neo4j: DEBUG
    io.weaviate: DEBUG
    org.eclipse.jgit: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 